# Generated by Django 4.1 on 2022-09-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_rename_news_1_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pubdate',
        ),
    ]
