# Generated by Django 4.1 on 2022-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_news_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
