# Generated by Django 4.1 on 2022-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_news_news_id_news_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='wenzhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=1500)),
                ('parent_id', models.IntegerField(default=0)),
                ('wenzhang_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
